IF DB_ID('DataWarehouse') IS NOT NULL
BEGIN
    ALTER DATABASE DataWarehouse SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DataWarehouse;
END;
GO

CREATE DATABASE DataWarehouse;
GO

USE DataWarehouse;
GO

-- VANPHONGDAIDIEN
CREATE TABLE VANPHONGDAIDIEN (
    MaTP VARCHAR(20) PRIMARY KEY,
    TenTP NVARCHAR(100),
    DiaChiVP NVARCHAR(200),
    Bang NVARCHAR(100),
    ThoiGianThanhLap DATETIME
);

-- CUAHANG
CREATE TABLE CUAHANG (
    MaCH VARCHAR(100) PRIMARY KEY,
    MaTP VARCHAR(20) NOT NULL,
    SoDienThoai VARCHAR(20),
    ThoiGianMoCua DATETIME,
    CONSTRAINT FK_CUAHANG_VPDD 
        FOREIGN KEY (MaTP) REFERENCES VANPHONGDAIDIEN(MaTP)
);

-- KHACHHANG
CREATE TABLE KHACHHANG (
    MaKH VARCHAR(20) PRIMARY KEY,
    TenKH NVARCHAR(150),
    MaTP VARCHAR(20),
    NgayDatHangDau DATE,
    LoaiKH CHAR(2),
    CONSTRAINT FK_KHACHHANG_VPDD 
        FOREIGN KEY (MaTP) REFERENCES VANPHONGDAIDIEN(MaTP),
    CONSTRAINT CK_LoaiKH 
        CHECK (LoaiKH IN ('DL', 'BD', 'CA'))
);

-- KHACHHANG_DULICH
CREATE TABLE KHACHHANG_DULICH (
    MaKH VARCHAR(20) PRIMARY KEY,
    HuongDanVien NVARCHAR(150),
    ThoiGianCuTru DATETIME,
    CONSTRAINT FK_KHDL_KH 
        FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
        ON DELETE CASCADE
);

-- KHACHHANG_BUUDIEN
CREATE TABLE KHACHHANG_BUUDIEN (
    MaKH VARCHAR(20) PRIMARY KEY,
    DiaChiBuuDien NVARCHAR(200),
    ThoiGianNhanHang DATETIME,
    CONSTRAINT FK_KHBD_KH 
        FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
        ON DELETE CASCADE
);

-- MATHANG
CREATE TABLE MATHANG (
    MaMH VARCHAR(50) PRIMARY KEY,
    MoTa NVARCHAR(255),
    KichCo VARCHAR(50),
    TrongLuong DECIMAL(10,2),
    Gia DECIMAL(15,2),
    ThoiGianNhapHang DATETIME
);

-- MHLUUTRU
CREATE TABLE MHLUUTRU (
    MaCH VARCHAR(100),
    MaMH VARCHAR(50),
    SoLuongTon INT,
    ThoiGianLuuTru DATETIME,
    CONSTRAINT PK_MHLUUTRU PRIMARY KEY (MaCH, MaMH),
    CONSTRAINT FK_MHLT_CH 
        FOREIGN KEY (MaCH) REFERENCES CUAHANG(MaCH),
    CONSTRAINT FK_MHLT_MH 
        FOREIGN KEY (MaMH) REFERENCES MATHANG(MaMH)
);

-- DONDATHANG
CREATE TABLE DONDATHANG (
    MaDon VARCHAR(20) PRIMARY KEY,
    NgayDatHang DATE,
    MaKH VARCHAR(20),
    CONSTRAINT FK_DDH_KH 
        FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);

-- MHDUOCDAT
CREATE TABLE MHDUOCDAT (
    MaDon VARCHAR(20),
    MaMH VARCHAR(50),
    SoLuongDat INT,
    GiaDat DECIMAL(15,2),
    ThoiGianDatHang DATETIME,
    CONSTRAINT PK_MHDUOCDAT PRIMARY KEY (MaDon, MaMH),
    CONSTRAINT FK_MHDD_DON 
        FOREIGN KEY (MaDon) REFERENCES DONDATHANG(MaDon)
        ON DELETE CASCADE,
    CONSTRAINT FK_MHDD_MH 
        FOREIGN KEY (MaMH) REFERENCES MATHANG(MaMH)
);